const $ = id => document.getElementById(id);
const num = id => Math.max(0, Number($(id)?.value || 0));
const money = n => "৳" + Math.round(n || 0).toLocaleString("en-BD");

const businessExpenses = [["Material purchase cost","bizMaterial"],["Salary / Wages Expense","bizSalary"],["Office Rent","bizOfficeRent"],["Utilities Expense","bizUtilities"],["Selling Expense","bizSelling"],["Sales Discount / Commission / Brokerage","bizSalesDiscount"],["Conference / Residential Cost of Sales Representative","bizConference"],["Administrative Expense","bizAdmin"],["Government Fee / Duty / Tax / Land Development Fee","bizGovFee"],["Repair & Maintenance","bizRepair"],["Insurance Premium","bizInsurance"],["C&F Expense","bizCNF"],["Mobile & Internet","bizMobile"],["Professional Expense","bizProfessional"],["Bad Debt","bizBadDebt"],["Advertisement","bizAdvertisement"],["Royalty / Technical / Head Office Expense","bizRoyalty"],["Depreciation Expense","bizDepreciation"],["Amortization Expense","bizAmortization"],["Research & Development","bizRnD"],["Employee Training","bizTraining"],["Conveyance","bizConveyance"],["Entertainment & Hospitality","bizEntertainment"],["Exchange Loss","bizExchange"],["Membership Fee","bizMembership"],["Foreign Travel","bizForeignTravel"],["Workers Welfare Fund","bizWelfare"],["Other Business Expense","bizOther"]];
$("businessExpenseGrid").innerHTML=businessExpenses.map(([label,id])=>`<label>${label}<input data-num id="${id}"></label>`).join("");

const rows=Array.from({length:12},(_,i)=>i+1);
$("aitTable").querySelector("tbody").innerHTML=rows.map(i=>`<tr><td><input data-aitref="${i}" placeholder="Period / reference"></td><td><input data-aitchallan="${i}"></td><td><input data-aitdate="${i}" type="date"></td><td><input data-aitamount="${i}" data-num class="ait-amount"></td></tr>`).join("");

function salary(){const gross=["basicPay","houseRent","festivalBonus","conveyance","medical","gratuity","employerPF","clothing","earnedLeave","performanceBonus"].reduce((s,id)=>s+num(id),0);const exempt=Math.min(gross/3,500000);const taxable=Math.max(0,gross-exempt);$("salaryGross").textContent=money(gross);$("salaryExempt").textContent=money(exempt);$("salaryTaxable").textContent=money(taxable);$("salaryLive").textContent=money(taxable);return taxable;}
function house(){const rent=num("rentIncome");const repair=$("houseType").value==="commercial"?rent*.30:$("houseType").value==="residential"?rent*.25:0;const expenses=["houseInsurance","houseInterest","municipalTax","vacancyAllowance","preRentInterest"].reduce((s,id)=>s+num(id),0)+repair;const taxable=Math.max(0,rent-expenses);$("houseRepair").textContent=money(repair);$("houseExpenses").textContent=money(expenses);$("houseTaxable").textContent=money(taxable);$("houseLive").textContent=money(taxable);return taxable;}
function agri(){const receipts=num("agriSales")+num("agriTea")*.60;const exp=["agriLandTax","agriLandRent","agriSeeds","agriLabour","agriIrrigation","agriInterest","agriMaintenance","agriInsurance","agriLoss","agriDep","agriDairy","agriOther"].reduce((s,id)=>s+num(id),0);const expenseIfNoBooks=$("agriBooks").value==="No"?receipts*.60:exp;const taxable=Math.max(0,receipts-expenseIfNoBooks);$("agriReceipts").textContent=money(receipts);$("agriExpenses").textContent=money(expenseIfNoBooks);$("agriTaxable").textContent=money(taxable);$("agriLive").textContent=money(taxable);return taxable;}
function business(){const receipts=["bizBusinessIncome","bizProfessionIncome","bizRecurring","bizManagement","bizLease","bizFx","bizLiquidated"].reduce((s,id)=>s+num(id),0);const expenses=businessExpenses.reduce((s,[,id])=>s+num(id),0);const taxable=Math.max(0,receipts-expenses);$("bizReceipts").textContent=money(receipts);$("bizExpenses").textContent=money(expenses);$("bizTaxable").textContent=money(taxable);$("businessLive").textContent=money(taxable);return taxable;}
function capital(){const sale=num("capitalSale");const acquisition=$("capitalOwnership").value==="purchase"?num("capitalPurchaseValue"):num("capitalFairValue");const expenses=num("capitalDuty")+acquisition+num("capitalRepair");const taxable=Math.max(0,sale-expenses);$("capitalExpenses").textContent=money(expenses);$("capitalTaxable").textContent=money(taxable);$("capitalLive").textContent=money(taxable);return taxable;}
function financial(){const gross=["finGovt","finSecurities","finInterest","finBank","finScheme","finDividend"].reduce((s,id)=>s+num(id),0);const exp=["finCharges","finLoanInterest","finOtherExpense"].reduce((s,id)=>s+num(id),0);const taxable=Math.max(0,gross-exp);$("finGross").textContent=money(gross);$("finExpenses").textContent=money(exp);$("finTaxable").textContent=money(taxable);$("financialLive").textContent=money(taxable);return taxable;}
function others(){const gross=["otherRoyalty","otherSubsidy","otherAlienation","otherGift","otherUnclassified"].reduce((s,id)=>s+num(id),0);const taxable=Math.max(0,gross-num("otherExpense"));$("otherGross").textContent=money(gross);$("otherTaxable").textContent=money(taxable);$("otherLive").textContent=money(taxable);return taxable;}
function taxForIncome(income){const sex=$("sex").value,disabled=$("disabled").value==="Yes",freedom=$("freedomFighter").value==="Yes",child=$("disableChild").value==="Yes";let threshold=freedom?525000:disabled?525000:child?450000:sex==="Female"?450000:400000;let rem=Math.max(0,income-threshold),tax=0;const bands=[[300000,.10],[400000,.15],[500000,.20],[2000000,.25],[Infinity,.30]];for(const [limit,rate] of bands){const x=Math.min(rem,limit);tax+=x*rate;rem-=x;if(rem<=0)break;}return tax;}
function investment(){const raw=num("invLife")+num("invAnnuity")+num("invPF")+num("invRPF")+num("invSuper")+Math.min(num("invGovt"),500000)+Math.min(num("invMutual"),500000)+Math.min(num("invDPS"),120000)+num("invBsec")+num("invHospital")+num("invHandicraft")+num("invZakat")+num("invBenevolent")+num("invEducation")+num("invSocio");const income=window.calc?.totalIncome||0;const maxInv=Math.round(income*.30);const eligible=Math.min(raw,maxInv);const rebate=Math.min(eligible*.10,income*.03,750000);$("eligibleInvestment").textContent=money(eligible);$("maxInvestment").textContent=money(maxInv);$("taxRebate").textContent=money(rebate);return rebate;}
function ait(){const total=[...document.querySelectorAll(".ait-amount")].reduce((s,e)=>s+Number(e.value||0),0)+num("aitIC")+num("aitFD");return total;}
function calculate(){const total=salary()+house()+agri()+business()+capital()+financial()+others();const tax=taxForIncome(total);window.calc={totalIncome:total,tax};$("totalIncome").textContent=money(total);$("taxBeforeRebate").textContent=money(tax);const rebate=investment();const afterRebate=Math.max(0,tax-rebate);$("estimatedTax").textContent=money(afterRebate);return{total,tax,rebate,afterRebate};}
function taxPayable(){const c=calculate();const turnover=num("taxTurnover")||num("bizTurnover");const turnoverTax=turnover*.01;const statutory=$("firstReturn").value==="Yes"?1000:5000;const payable=Math.max(turnoverTax,c.afterRebate,statutory);const credits=ait()+num("otherAITCredit");const balance=Math.max(0,payable-credits);$("taxTurnover").value=turnover||"";$("turnoverMinimum").value=Math.round(turnoverTax);$("regularTaxDisplay").value=Math.round(c.afterRebate);$("statutoryMinimumDisplay").value=statutory;$("taxPayableBeforeAIT").value=Math.round(payable);$("turnoverMinimumSummary").textContent=money(turnoverTax);$("regularTaxSummary").textContent=money(c.afterRebate);$("minimumTaxSummary").textContent=money(statutory);$("finalTaxPayable").textContent=money(payable);$("totalAITPayment").value=Math.round(credits);$("balanceTaxPayable").textContent=money(balance);const paid=num("amountPaid");$("remainingAmount").value=Math.max(0,balance-paid);window.calc={...c,turnover,turnoverTax,statutory,payable,credits,balance,paid,remaining:Math.max(0,balance-paid)};return window.calc;}
function buildReview(){const c=taxPayable();const rows=[["Assessee",$("name").value||"Not provided"],["Assessment Year",$("assessmentYear").value],["TIN",$("tin").value||"Not provided"],["Total Taxable Income",money(c.total)],["Regular Calculated Tax",money(c.afterRebate)],["1% of Business Turnover",money(c.turnoverTax)],["Applicable Minimum Tax",money(c.statutory)],["Tax Payable Before AIT",money(c.payable)],["AIT / Tax Credit",money(c.credits)],["Balance Tax Payable",money(c.balance)],["Amount Paid",money(c.paid)],["Remaining Amount",money(c.remaining)]];$("reviewCard").innerHTML=`<div class="review-header"><h3>Final Computation Summary</h3><div>Assessment Year ${$("assessmentYear").value}</div></div><div class="review-grid">${rows.map(r=>`<div><small>${r[0]}</small><strong>${r[1]}</strong></div>`).join("")}</div>`;$("sigName").textContent=$("name").value||"________________";$("signaturePreview").innerHTML=`<h3>Client approval requested</h3><p>I have reviewed the computation prepared from the information and documents supplied by me.</p><div class="amount">${money(c.balance)}</div><div>Balance tax payable after available AIT / credits</div>`;}
function allCalc(){calculate();if($("taxTurnover"))taxPayable();if(document.querySelector('[data-panel="5"].active')||document.querySelector('[data-panel="6"].active'))buildReview();}
document.addEventListener("input",e=>{if(e.target.matches("input,select,textarea"))allCalc();});document.addEventListener("change",e=>{if(e.target.matches("input,select,textarea"))allCalc();});
document.querySelectorAll(".step").forEach(b=>b.addEventListener("click",()=>showStep(Number(b.dataset.step))));document.querySelectorAll(".next").forEach(b=>b.addEventListener("click",()=>{const a=Number(document.querySelector(".step-panel.active").dataset.panel);showStep(Math.min(6,a+1));}));document.querySelectorAll(".prev").forEach(b=>b.addEventListener("click",()=>{const a=Number(document.querySelector(".step-panel.active").dataset.panel);showStep(Math.max(1,a-1));}));
function showStep(n){document.querySelectorAll(".step-panel").forEach(p=>p.classList.toggle("active",Number(p.dataset.panel)===n));document.querySelectorAll(".step").forEach(p=>p.classList.toggle("active",Number(p.dataset.step)===n));if(n===4)taxPayable();if(n===5||n===6)buildReview();window.scrollTo({top:0,behavior:"smooth"});}
function snapshot(){const data={};document.querySelectorAll("input,select,textarea").forEach(e=>{if(e.id)data[e.id]=e.type==="checkbox"?e.checked:e.value;});data.ait=[...document.querySelectorAll("#aitTable tbody tr")].map(tr=>({ref:tr.querySelector("[data-aitref]")?.value||"",challan:tr.querySelector("[data-aitchallan]")?.value||"",date:tr.querySelector("[data-aitdate]")?.value||"",amount:tr.querySelector("[data-aitamount]")?.value||""}));return data;}
function restore(data){Object.keys(data).forEach(id=>{const e=$(id);if(e&&!['ait'].includes(id)){if(e.type==="checkbox")e.checked=!!data[id];else e.value=data[id];}});(data.ait||[]).forEach((x,i)=>{const tr=document.querySelectorAll("#aitTable tbody tr")[i];if(!tr)return;tr.querySelector("[data-aitref]").value=x.ref||"";tr.querySelector("[data-aitchallan]").value=x.challan||"";tr.querySelector("[data-aitdate]").value=x.date||"";tr.querySelector("[data-aitamount]").value=x.amount||"";});allCalc();buildReview();}
$("saveBtn").addEventListener("click",()=>{localStorage.setItem("clientTaxDraft",JSON.stringify(snapshot()));$("status").textContent="Draft saved in this browser.";$("status").classList.remove("hidden");});$("loadBtn").addEventListener("click",()=>{const x=localStorage.getItem("clientTaxDraft");if(!x){$("status").textContent="No saved draft was found in this browser.";$("status").classList.remove("hidden");return;}restore(JSON.parse(x));$("status").textContent="Draft loaded.";$("status").classList.remove("hidden");});$("printBtn").addEventListener("click",()=>{buildReview();showStep(6);setTimeout(()=>window.print(),150);});$("finalPrintBtn").addEventListener("click",()=>window.print());allCalc();
