const $=id=>document.getElementById(id);const num=id=>Math.max(0,Number($(id)?.value||0));const money=n=>"৳"+Math.round(n||0).toLocaleString("en-BD");
const businessExpenses=[["Material purchase cost","bizMaterial"],["Salary / Wages Expense","bizSalary"],["Office Rent","bizOfficeRent"],["Utilities Expense","bizUtilities"],["Selling Expense","bizSelling"],["Sales Discount / Commission / Brokerage","bizSalesDiscount"],["Conference / Residential Cost of Sales Representative","bizConference"],["Administrative Expense","bizAdmin"],["Government Fee / Duty / Tax / Land Development Fee","bizGovFee"],["Repair & Maintenance","bizRepair"],["Insurance Premium","bizInsurance"],["C&F Expense","bizCNF"],["Mobile & Internet","bizMobile"],["Professional Expense","bizProfessional"],["Bad Debt","bizBadDebt"],["Advertisement","bizAdvertisement"],["Royalty / Technical / Head Office Expense","bizRoyalty"],["Depreciation Expense","bizDepreciation"],["Amortization Expense","bizAmortization"],["Research & Development","bizRnD"],["Employee Training","bizTraining"],["Conveyance","bizConveyance"],["Entertainment & Hospitality","bizEntertainment"],["Exchange Loss","bizExchange"],["Membership Fee","bizMembership"],["Foreign Travel","bizForeignTravel"],["Workers Welfare Fund","bizWelfare"],["Other Business Expense","bizOther"]];
$("businessExpenseGrid").innerHTML=businessExpenses.map(([l,id])=>`<label>${l}<input data-num id="${id}"></label>`).join("");
const months=["Jul-25","Aug-25","Sep-25","Oct-25","Nov-25","Dec-25","Jan-26","Feb-26","Mar-26","Apr-26","May-26","Jun-26"];
$("aitTable").querySelector("tbody").innerHTML=months.map(m=>`<tr><td><input data-ait="${m}" placeholder="Free text: period / reference"></td><td><input data-challan="${m}"></td><td><input data-aitdate="${m}" type="date"></td><td><input data-aitamount="${m}" data-num class="ait-amount"></td></tr>`).join("");
function salary(){let gross=["basicPay","houseRent","festivalBonus","conveyance","medical","gratuity","employerPF","clothing","earnedLeave","performanceBonus","salaryOther"].reduce((s,id)=>s+num(id),0),ex=Math.min(gross/3,500000),taxable=Math.max(0,gross-ex);$("salaryGross").textContent=money(gross);$("salaryExempt").textContent=money(ex);$("salaryTaxable").textContent=money(taxable);$("salaryLive").textContent=money(taxable);return taxable}
function house(){let r=num("rentIncome"),repair=$("houseType").value==="commercial"?r*.30:$("houseType").value==="residential"?r*.25:0,e=["houseInsurance","houseInterest","municipalTax","vacancyAllowance","preRentInterest"].reduce((s,id)=>s+num(id),0)+repair,t=Math.max(0,r-e);$("houseRepair").textContent=money(repair);$("houseExpenses").textContent=money(e);$("houseTaxable").textContent=money(t);$("houseLive").textContent=money(t);return t}
function agri(){let r=num("agriSales")+num("agriTea")*.60,e=["agriLandTax","agriLandRent","agriSeeds","agriLabour","agriIrrigation","agriInterest","agriMaintenance","agriInsurance","agriLoss","agriDep","agriDairy","agriOther"].reduce((s,id)=>s+num(id),0);if($("agriBooks").value==="No")e=r*.60;let t=Math.max(0,r-e);$("agriReceipts").textContent=money(r);$("agriExpenses").textContent=money(e);$("agriTaxable").textContent=money(t);$("agriLive").textContent=money(t);return t}
function business(){let r=["bizBusinessIncome","bizProfessionIncome","bizRecurring","bizManagement","bizLease","bizFx","bizLiquidated"].reduce((s,id)=>s+num(id),0),e=businessExpenses.reduce((s,[,id])=>s+num(id),0),t=Math.max(0,r-e);$("bizReceipts").textContent=money(r);$("bizExpenses").textContent=money(e);$("bizTaxable").textContent=money(t);$("businessLive").textContent=money(t);return t}
function capital(){let sale=num("capitalSale"),acq=$("capitalOwnership").value==="purchase"?num("capitalPurchaseValue"):num("capitalFairValue"),e=acq+num("capitalDuty")+num("capitalRepair"),t=Math.max(0,sale-e);$("capitalExpenses").textContent=money(e);$("capitalTaxable").textContent=money(t);$("capitalLive").textContent=money(t);return t}
function financial(){let g=["finGovt","finSecurities","finInterest","finBank","finScheme","finDividend"].reduce((s,id)=>s+num(id),0),e=["finCharges","finLoanInterest","finOtherExpense"].reduce((s,id)=>s+num(id),0),t=Math.max(0,g-e);$("finGross").textContent=money(g);$("finExpenses").textContent=money(e);$("finTaxable").textContent=money(t);$("financialLive").textContent=money(t);return t}
function others(){let g=["otherRoyalty","otherSubsidy","otherAlienation","otherGift","otherUnclassified"].reduce((s,id)=>s+num(id),0),t=Math.max(0,g-num("otherExpense"));$("otherGross").textContent=money(g);$("otherTaxable").textContent=money(t);$("otherLive").textContent=money(t);return t}
function taxForIncome(income){let threshold=$("freedomFighter").value==="Yes"?525000:$("disabled").value==="Yes"?525000:$("disableChild").value==="Yes"?450000:$("sex").value==="Female"?450000:400000,rem=Math.max(0,income-threshold),tax=0;for(const [limit,rate] of [[300000,.10],[400000,.15],[500000,.20],[2000000,.25],[Infinity,.30]]){let x=Math.min(rem,limit);tax+=x*rate;rem-=x;if(rem<=0)break}return tax}
function investment(){let raw=["invLife","invAnnuity","invPF","invRPF","invSuper","invBsec","invHospital","invHandicraft","invZakat","invBenevolent","invEducation","invSocio"].reduce((s,id)=>s+num(id),0)+Math.min(num("invGovt"),500000)+Math.min(num("invMutual"),500000)+Math.min(num("invDPS"),120000),income=state.totalIncome||0,max=income*.30,eligible=Math.min(raw,max),rebate=Math.min(eligible*.10,income*.03,750000);$("eligibleInvestment").textContent=money(eligible);$("maxInvestment").textContent=money(max);$("taxRebate").textContent=money(rebate);state.totalInvestment=raw;state.eligibleInvestment=eligible;return rebate}
function ait(){return [...document.querySelectorAll(".ait-amount")].reduce((s,e)=>s+Number(e.value||0),0)+num("otherAITCredit")}
const state={};
function assetCalc(){const assets=["assetCash","assetInvestment","assetProperty","assetVehicle","assetBusiness","assetShares","assetJewellery","assetOther"].reduce((s,id)=>s+num(id),0),liab=["liabBank","liabPersonal","liabBusiness","liabOther"].reduce((s,id)=>s+num(id),0),net=assets-liab,prev=num("prevNetAsset"),change=net-prev,rec=num("netAssetAdditions")-num("netAssetDisposals")+num("netAssetOthers"),diff=change-rec;const setText=(id,v)=>{const e=$(id);if(e)e.textContent=money(v)},setValue=(id,v)=>{const e=$(id);if(e)e.value=Math.round(v)};setText("thisYearAssets",assets);setText("thisYearLiabilities",liab);setText("thisYearNetAsset",net);setValue("reconPrevious",prev);setValue("reconCurrent",net);setValue("netAssetChange",change);setText("reconciledChange",rec);setText("reconciliationDifference",diff);state.assets=assets;state.liabilities=liab;state.netAsset=net;state.prevNetAsset=prev;state.netAssetChange=change;state.reconciledChange=rec;state.reconciliationDifference=diff}
function calculate(){let total=salary()+house()+agri()+business()+capital()+financial()+others(),before=taxForIncome(total);state.totalIncome=total;state.taxBeforeRebate=before;let rebate=investment(),calculatedAfterRebate=Math.max(0,before-rebate),turnover=num("bizTurnover"),one=turnover*.01,min=$("firstReturn").value==="Yes"?1000:5000,regularTaxAfterRebate=Math.max(calculatedAfterRebate,min),taxPay=Math.max(one,regularTaxAfterRebate,min),credit=ait(),balance=Math.max(0,taxPay-credit);if($("taxTurnover")){ $("taxTurnover").value=Math.round(turnover); $("taxTurnover").readOnly=true; }$("turnoverMinimum").value=Math.round(one);$("regularTaxDisplay").value=Math.round(regularTaxAfterRebate);$("statutoryMinimumDisplay").value=min;$("taxPayableBeforeAIT").value=Math.round(taxPay);$("balanceTaxPayable").value=Math.round(balance);$("turnoverMinimumSummary").textContent=money(one);$("regularTaxSummary").textContent=money(regularTaxAfterRebate);$("minimumTaxSummary").textContent=money(min);$("finalTaxPayable").textContent=money(taxPay);$("totalAITPayment").value=Math.round(credit);if($("balanceTaxPayable2"))$("balanceTaxPayable2").textContent=money(balance);$("estimatedTax").textContent=money(taxPay);if($("remainingAmount"))$("remainingAmount").value=Math.max(0,balance-num("amountPaid"));state.rebate=rebate;state.calculatedAfterRebate=calculatedAfterRebate;state.regularTax=regularTaxAfterRebate;state.turnover=turnover;state.turnoverMinimum=one;state.minimumTax=min;state.taxPayable=taxPay;state.ait=credit;state.balance=balance;assetCalc();return state}
function review(){calculate();const rows=[["Assessee",$("name").value||"Not provided"],["Assessment Year",$("assessmentYear").value],["TIN",$("tin").value||"Not provided"],["Total Income",money(state.totalIncome)],["Total Investment",money(state.totalInvestment)],["Eligible Investment",money(state.eligibleInvestment)],["Tax Without Investment Rebate",money(state.taxBeforeRebate)],["Investment Tax Rebate",money(state.rebate)],["Tax Considering Investment Rebate",money(state.calculatedAfterRebate)],["Regular Tax After Rebate / Minimum Tax",money(state.regularTax)],["1% of Business Turnover",money(state.turnoverMinimum)],["Tax to Deposit",money(state.taxPayable)],["Tax Paid / AIT / Credit",money(state.ait)],["Tax Payable",money(state.balance)],["Previous Year Net Asset",money(state.prevNetAsset)],["This Year Total Assets",money(state.assets)],["This Year Total Liabilities",money(state.liabilities)],["This Year Net Asset",money(state.netAsset)],["Increase / (Decrease) in Net Asset",money(state.netAssetChange)],["Reconciled Change",money(state.reconciledChange)],["Reconciliation Difference",money(state.reconciliationDifference)]];const card=$("reviewCard");if(card)card.innerHTML=`<div class="review-header"><h3>Final Tax Calculation & Asset-Liability Summary</h3><div>Assessment Year ${$("assessmentYear").value}</div></div><div class="review-grid">${rows.map(r=>`<div><small>${r[0]}</small><strong>${r[1]}</strong></div>`).join("")}</div>`;if($("sigName"))$("sigName").textContent=$("name").value||"________________";if($("signaturePreview"))$("signaturePreview").innerHTML=`<h3>Client approval requested</h3><p>I have reviewed the income, investment, tax calculation, payment and asset-liability reconciliation.</p><div class="amount">Tax to Deposit: ${money(state.taxPayable)}</div><div>Tax Paid / AIT / Credit: ${money(state.ait)} &nbsp; | &nbsp; Balance Tax Payable: ${money(state.balance)}</div>`}
function showStep(n){document.querySelectorAll(".step-panel").forEach(p=>p.classList.toggle("active",Number(p.dataset.panel)===n));document.querySelectorAll(".step").forEach(p=>p.classList.toggle("active",Number(p.dataset.step)===n));if(n===6)review();window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".step").forEach(b=>b.onclick=()=>showStep(+b.dataset.step));document.querySelectorAll(".next").forEach(b=>b.onclick=()=>showStep(Math.min(6,+document.querySelector(".step-panel.active").dataset.panel+1)));document.querySelectorAll(".prev").forEach(b=>b.onclick=()=>showStep(Math.max(1,+document.querySelector(".step-panel.active").dataset.panel-1)));document.addEventListener("input",e=>{if(e.target.matches("input,select,textarea"))calculate()});document.addEventListener("change",e=>{if(e.target.matches("input,select,textarea"))calculate()});
function snapshot(){let data={};document.querySelectorAll("input,select,textarea").forEach(e=>{if(e.id)data[e.id]=e.type==="checkbox"?e.checked:e.value});data.ait=[...document.querySelectorAll("[data-ait]")].map(e=>({ref:e.dataset.ait,value:e.value,challan:$("[data-challan='"+e.dataset.ait+"']")?.value||"",date:$("[data-aitdate='"+e.dataset.ait+"']")?.value||"",amount:$("[data-aitamount='"+e.dataset.ait+"']")?.value||""}));return data}
function restore(d){Object.keys(d).forEach(id=>{let e=$(id);if(e){if(e.type==="checkbox")e.checked=!!d[id];else e.value=d[id]}});(d.ait||[]).forEach(x=>{let a=$("[data-ait='"+x.ref+"']"),c=$("[data-challan='"+x.ref+"']"),dt=$("[data-aitdate='"+x.ref+"']"),am=$("[data-aitamount='"+x.ref+"']");if(a)a.value=x.value;if(c)c.value=x.challan;if(dt)dt.value=x.date;if(am)am.value=x.amount});calculate();review()}
$("saveBtn").onclick=()=>{localStorage.setItem("clientTaxDraft",JSON.stringify(snapshot()));$("status").textContent="Draft saved in this browser.";$("status").classList.remove("hidden")};$("loadBtn").onclick=()=>{let d=localStorage.getItem("clientTaxDraft");if(d)restore(JSON.parse(d));else{$("status").textContent="No saved draft found.";$("status").classList.remove("hidden")}};$("printBtn").onclick=()=>{showStep(6);setTimeout(()=>window.print(),150)};$("finalPrintBtn").onclick=()=>window.print();calculate();
// Final review safeguard: the review panel must always render the complete calculation summary, even when optional asset/liability fields are not present.
setTimeout(()=>{try{calculate();if(document.querySelector('.step-panel.active')?.dataset.panel==='6')review()}catch(e){console.error('Tax calculation safeguard:',e)}},0);